### ISSUE TITLE
Problem with https

### ISSUE THREAD

**Issue by ss017228** [Probesys/glpi-plugins-projectbridge#7]
![Immagine 2020-11-23 131848](https://user-images.githubusercontent.com/67052260/99961303-749d3d80-2d8e-11eb-9221-9cbeba1924e9.png)
URL Not Found when using GLPI with SSL

**Comment by philg38** [comment]
Hi ss017228,
thanks for this issue. Can you be more precise with this https problem ?
wich url make this error ? 
what is your glpi version ?
what is your project bridge plugin version ?

**Comment by ss017228** [comment]
Hi Phil
problem found, i have installed version 2.2.0 from the marketplace on GLPI 9.5.2 when i click on the link "ProjectBridge project tasks" in the menu "Tools" i get the url "https://glpitest.amaroma.it/plugins/projectbridge/front/projecttask.php", after a search on the server the path of projectbridge is /marketplace/projectbridge/front/projecttask.php. The plugin work after copying all in the plugins folder, but i don't know if this is the correct solution.

**Comment by philg38** [comment]
Hi Sirio,
i think the problem is that you had certainly previoulsy install the _plugins_ with the classique method, so the files are in the plugin folder and now, you have upgrade it with the marketplace method.
All the link in the plugin use the constant PLUGIN_PROJECTBRIDGE_WEB_DIR. The value of this constant is different if the plugin is install with marketplace or with the classique method.

**Comment by felag** [comment]
@ss017228 Feel free to reopen this issue if you are still impacted.
